import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
       {/* Force-loading the font */}
       <link
          rel="preconnect"
          href="https://fonts.cdnfonts.com"
        />
        <link
          rel="stylesheet"
          href="https://fonts.cdnfonts.com/css/geist-sans"
        />
      </head>
      <body
        className="font-geist"
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
